spring:
  application:
    name: hello-server

server:
  port: 8071
  


eureka:
  client:
      registerWithEureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost   